# Generated by Django 5.1.2 on 2025-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='cooks',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
        migrations.DeleteModel(
            name='RestaurantInfo',
        ),
        migrations.DeleteModel(
            name='Cook',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
